Adjuncts:
    type: entity
    table: adjuncts
    fields:
        id:
            id: true
            type: integer
            unsigned: true
            nullable: false
            generator:
                strategy: IDENTITY
        adjunctname:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: adjunctName
        adjunctorigin:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: adjunctOrigin
        adjunctsupplier:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: adjunctSupplier
        adjunctinfo:
            type: text
            nullable: true
            column: adjunctInfo
        adjunctppg:
            type: decimal
            nullable: false
            column: adjunctPPG
        adjunctlovibondlow:
            type: decimal
            nullable: false
            column: adjunctLovibondLow
        adjunctlovibondhigh:
            type: decimal
            nullable: false
            column: adjunctLovibondHigh
    lifecycleCallbacks: {  }
