Brewerlinks:
    type: entity
    table: brewerlinks
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        brewerlinkname:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerLinkName
        brewerlinkurl:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerLinkURL
    lifecycleCallbacks: {  }
