Brewer:
    type: entity
    table: brewer
    fields:
        id:
            id: true
            type: boolean
            nullable: false
            generator:
                strategy: IDENTITY
        brewerfirstname:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerFirstName
        brewerlastname:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerLastName
        brewermiddlename:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerMiddleName
        brewerprefix:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerPrefix
        brewersuffix:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerSuffix
        brewerage:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerAge
        brewercity:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerCity
        brewerstate:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerState
        brewercountry:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerCountry
        brewerabout:
            type: text
            nullable: true
            column: brewerAbout
        brewerlogname:
            type: string
            length: 200
            fixed: false
            nullable: false
            column: brewerLogName
        brewertagline:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerTagline
        brewerfavstyles:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerFavStyles
        brewerprefmethod:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerPrefMethod
        brewerclubs:
            type: text
            nullable: true
            column: brewerClubs
        brewerother:
            type: text
            nullable: true
            column: brewerOther
        brewerimage:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: brewerImage
    lifecycleCallbacks: {  }
