Brewingcss:
    type: entity
    table: brewingcss
    fields:
        id:
            id: true
            type: boolean
            nullable: false
            generator:
                strategy: IDENTITY
        theme:
            type: string
            length: 250
            fixed: false
            nullable: false
        themename:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: themeName
        themecolor1:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: themeColor1
        themecolor2:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: themeColor2
    lifecycleCallbacks: {  }
