EquipProfiles:
    type: entity
    table: equip_profiles
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        equipprofilename:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: equipProfileName
        equipbatchsize:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipBatchSize
        equipboilvolume:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipBoilVolume
        equipevaprate:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipEvapRate
        equiploss:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipLoss
        equipnotes:
            type: text
            nullable: true
            column: equipNotes
        equipmashtunvolume:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipMashTunVolume
        equipmashtunweight:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipMashTunWeight
        equipmashtunmaterial:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: equipMashTunMaterial
        equipmashtunspecificheat:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipMashTunSpecificHeat
        equipmashtundeadspace:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipMashTunDeadspace
        equiphoputil:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipHopUtil
        equiptypicalefficiency:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipTypicalEfficiency
        equiptopup:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipTopUp
        equiptopupkettle:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipTopUpKettle
        equipbrewerid:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: equipBrewerID
        equiptypicalwaterratio:
            type: string
            length: 10
            fixed: false
            nullable: true
            column: equipTypicalWaterRatio
    lifecycleCallbacks: {  }
