Misc:
    type: entity
    table: misc
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        miscname:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: miscName
        misctype:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: miscType
        miscuse:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: miscUse
        miscnotes:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: miscNotes
    lifecycleCallbacks: {  }
