Preferences:
    type: entity
    table: preferences
    fields:
        id:
            id: true
            type: boolean
            nullable: false
            generator:
                strategy: IDENTITY
        measfluid1:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: measFluid1
        measfluid2:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: measFluid2
        measweight1:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: measWeight1
        measweight2:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: measWeight2
        measwatergrainratio:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: measWaterGrainRatio
        meastemp:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: measTemp
        meascolor:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: measColor
        measbitter:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: measBitter
        measabbrev:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: measAbbrev
        allowreviews:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowReviews
        allowprintlog:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowPrintLog
        allowprintrecipe:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowPrintRecipe
        allowprintxml:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowPrintXML
        allowspecifics:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowSpecifics
        allowgeneral:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowGeneral
        allowcomments:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowComments
        allowrecipe:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowRecipe
        allowmash:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowMash
        allowwater:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowWater
        allowprocedure:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowProcedure
        allowspecialprocedure:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowSpecialProcedure
        allowfermentation:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowFermentation
        allowlabel:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowLabel
        allowrelated:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowRelated
        allowlist:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowList
        allowstatus:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowStatus
        allowupcoming:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowUpcoming
        allowawards:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowAwards
        allowcalendar:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowCalendar
        allownews:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowNews
        allowprofile:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: allowProfile
        theme:
            type: string
            length: 250
            fixed: false
            nullable: true
        mode:
            type: string
            length: 1
            fixed: true
            nullable: true
        home:
            type: string
            length: 250
            fixed: false
            nullable: true
        menuhome:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuHome
        menubrewblogs:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuBrewBlogs
        menurecipes:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuRecipes
        menuawards:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuAwards
        menuabout:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuAbout
        menureference:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuReference
        menucalculators:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuCalculators
        menucalendar:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuCalendar
        menulogin:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuLogin
        menulogout:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuLogout
        menumembers:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: menuMembers
        mashdisplaymethod:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: mashDisplayMethod
        waterdisplaymethod:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: waterDisplayMethod
        hoppelletfactor:
            type: float
            nullable: false
            column: hopPelletFactor
    lifecycleCallbacks: {  }
