Reviews:
    type: entity
    table: reviews
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        brewid:
            type: boolean
            nullable: true
            column: brewID
        brewscoredate:
            type: date
            nullable: true
            column: brewScoreDate
        brewaromascore:
            type: boolean
            nullable: true
            column: brewAromaScore
        brewaromainfo:
            type: text
            nullable: true
            column: brewAromaInfo
        brewappearancescore:
            type: boolean
            nullable: true
            column: brewAppearanceScore
        brewappearanceinfo:
            type: text
            nullable: true
            column: brewAppearanceInfo
        brewflavorscore:
            type: boolean
            nullable: true
            column: brewFlavorScore
        brewflavorinfo:
            type: text
            nullable: true
            column: brewFlavorInfo
        brewmouthfeelscore:
            type: boolean
            nullable: true
            column: brewMouthfeelScore
        brewmouthfeelinfo:
            type: text
            nullable: true
            column: brewMouthfeelInfo
        brewoverallscore:
            type: boolean
            nullable: true
            column: brewOverallScore
        brewoverallinfo:
            type: text
            nullable: true
            column: brewOverallInfo
        brewscoredby:
            type: string
            length: 250
            fixed: false
            nullable: true
            column: brewScoredBy
        brewbrewerid:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: brewBrewerID
        brewscorerlevel:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: brewScorerLevel
    lifecycleCallbacks: {  }
